#!/usr/bin/python3
"""
Generator functions to stream and process user data in batches.
Revised to strictly avoid the 'return' keyword.
"""
import mysql.connector
import sys

# --- Configuration (Must match the settings in seed.py) ---
MYSQL_USER = "root"
MYSQL_PASSWORD = "your_mysql_password"  # <--- UPDATE THIS
MYSQL_HOST = "localhost"
DATABASE_NAME = "ALX_prodev"
# ---------------------------------------------------------

def stream_users_in_batches(batch_size):
    """
    Connects to the ALX_prodev database and streams rows in batches
    from the user_data table using a generator.

    Args:
        batch_size (int): The number of rows to fetch in each batch.

    Yields:
        list[dict]: A list of user rows (the batch).
    """
    connection = None
    try:
        # Establish connection to the database
        connection = mysql.connector.connect(
            host=MYSQL_HOST,
            user=MYSQL_USER,
            password=MYSQL_PASSWORD,
            database=DATABASE_NAME
        )
        
        cursor = connection.cursor(dictionary=True)
        select_query = "SELECT user_id, name, email, age FROM user_data"
        cursor.execute(select_query)

        # Loop 1: Continually fetch results until no more rows are left
        while True:
            # fetchmany() fetches up to batch_size rows.
            batch = cursor.fetchmany(batch_size)
            
            if not batch:
                # No more rows left to fetch, exit the loop
                break
            
            # Yield the batch (list of dicts)
            yield batch
            
    except mysql.connector.Error as err:
        # On error, print message and let the function terminate implicitly.
        print(f"Database error: {err}", file=sys.stderr)
        
    except Exception as e:
        # On error, print message and let the function terminate implicitly.
        print(f"An unexpected error occurred: {e}", file=sys.stderr)
        
    finally:
        # Ensure the connection and cursor are closed
        if 'cursor' in locals() and cursor:
            cursor.close()
        if connection and connection.is_connected():
            connection.close()

def batch_processing(batch_size):
    """
    Processes each batch of users from the generator, filtering for
    users over the age of 25.

    Args:
        batch_size (int): The size of the batches to fetch.

    Yields:
        dict: A single user dictionary where age > 25.
    """
    # Loop 2: Iterate over the batches generated by stream_users_in_batches
    for batch in stream_users_in_batches(batch_size):
        # Loop 3: Iterate over the individual users within the current batch
        for user in batch:
            # Filter the users
            if user.get('age', 0) > 25: 
                # Yield the single processed user
                yield user


if __name__ == '__main__':
    BATCH_SIZE = 50
    processed_users_generator = batch_processing(BATCH_SIZE)
    
    print(f"--- Processing users in batches of {BATCH_SIZE} (Age > 25) ---")
    
    count = 0
    for user in processed_users_generator:
        print(user)
        count += 1
        if count >= 10:
            break
